app/__init__.py
from flask import Flask
from config import Config

from flask_sqlalchemy import SQLAlchemy 
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS


app = Flask(__name__)


CORS(app)


app.config.from_object(Config)

root_db.init_app(app)
login_manager.init_app(app)

ma.init_app(app)
migrate = Migrate(app, root_db)

from helpers import JSONEncoder
app.json_encoder = JSONEncoder







from .auth.routes import auth
from .site.routes import site
from .api.routes import api


app.register_blueprint(auth)
app.register_blueprint(site)
app.register_blueprint(api)

app/api/routes.py
from flask import Blueprint, request, jsonify, render_template, json
from helpers import token_required
from models import db, User, Meme, meme_schema, memes_schema, PictureState
from flask_login import current_user
from helpers import save_picture, delete_picture



api = Blueprint('api', __name__, url_prefix = '/api', template_folder= 'api_templates')

pic = PictureState()


@api.route('/memes-picture', methods= ['GET'])
@token_required
def get_pic_path(current_token):
    print(pic.pic_path)
    pic_dict = {'pic_path': pic.pic_path}
    return jsonify(pic_dict)



@api.route('/memes-picture', methods= ['POST'])
@token_required
def save_meme_picture(current_token):
    given_file = request.files['file']
    meme_file = save_picture(given_file, 'meme_photos')
    pic.setPic(meme_file)
    print(pic.pic_path)
    return jsonify(meme_file)


@api.route('/memes', methods= ['POST'])
@token_required
def create_meme(current_token):


    meme_pic = request.json['file']
    content_top = request.json['content_top']
    content_bottom = request.json['content_bottom']
    public = request.json['public']

    user_token = current_token.token




    print(f'BIG TESTER: {current_token.token}')

    meme = Meme(meme_pic, content_top = content_top, content_bottom = content_bottom, public=public, user_token = user_token)
    db.session.add(meme)
    db.session.commit()
    response = meme_schema.dump(meme)
    return jsonify(response)

#display all cars
@api.route('/memes', methods= ['GET'])
@token_required
def display_cars(current_token):

    user = current_token.token
    memes = Meme.query.filter_by(user_token = user).all()
    response = memes_schema.dump(memes)
    return jsonify(response)

# display a single car
@api.route('/meme/<id>', methods= ['GET'])
@token_required
def get_single_car(current_token, id):
    meme = Meme.query.get(id)
    response = meme_schema.dump(meme)
    return jsonify(response)


#update a particular car
@api.route('meme/<id>', methods = ['POST', 'PUT'])
@token_required
def update_car(current_token, id):
   meme = Meme.query.get(id)
   meme.content_top = request.json['content_top']
   meme.content_bottom = request.json['content_bottom']
   print(request.json['content_top'])

#    meme.picture = request.json['picture']
   meme.user_token = current_token.token

   db.session.commit()
   response = meme_schema.dump(meme)
   return jsonify(response)

# deleates a particular meme
@api.route('/meme/<id>', methods = ['DELETE'])
@token_required
def delete_car(current_token, id):

    meme = Meme.query.get(id)
    db.session.delete(meme)
    db.session.commit()

    delete_picture(meme, 'meme_photos')

    
    response = meme_schema.dump(meme)
    return jsonify(response)



#create a collection route 
#create an all memes route

app/site/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from forms import  AddMemeForm, UpdateAccountForm
from models import  Meme, db
from flask_login import current_user, login_required
from helpers import save_picture


site = Blueprint('site', __name__, template_folder = 'site_templates')


@site.route('/')
@site.route('/home')
def home():
    memes = Meme.query.all()
    return render_template('home.html', pics = memes)





@site.route('/add_meme', methods = ['GET','POST'])
@login_required
def add_meme():
    form = AddMemeForm()
    if form.validate_on_submit():
        meme_file = save_picture(form.picture.data, 'meme_photos')
        meme = Meme(meme_file, current_user.token, form.public.data)
        db.session.add(meme)
        db.session.commit()
        flash('You have succesfully added a meme to your collection', 'success')
        return redirect(url_for('site.home'))
    return render_template('meme.html', form = form)
    


@site.route('/account', methods = ["GET", 'POST'])
@login_required
def account():
    form = UpdateAccountForm()

    if form.validate_on_submit():
        if form.picture.data:
                
            picture_file = save_picture(form.picture.data, 'profile_pics')
            current_user.profile_photo = picture_file


        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('site.account'))
    
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    profile_photo = url_for('static', filename = 'profile_pics/' + current_user.profile_photo)
    return render_template('account.html', image_file = profile_photo, form = form)

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="static/main.css">

    {% if title %}
        <title>Meme App - {{ title }}</title>
    {% else %}
        <title>Meme App</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{url_for('site.home')}}">Home</a>
              <a class="nav-item nav-link" href="#">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{url_for('site.add_meme')}}">Add Meme</a>
                <a class="nav-item nav-link" href="{{url_for('site.account')}}">Account</a>
                <a class="nav-item nav-link" href="{{url_for('auth.logout')}}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{{url_for('auth.login')}}">Login</a>
                <a class="nav-item nav-link" href="{{url_for('auth.register')}}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
        <center>
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
        </center>
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>